name: Synk All Forks

# Controls when the workflow will run
on:
  schedule:
    - cron:  '30 2 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Synk Forks
      shell: bash -O extglob {0}
      run: |
        echo "Auth"
        echo ${{ secrets.synk_token }} | gh auth login --with-token
        echo ${{ secrets.synk_token }} > ghtoken
        
        #gh repo list ${{ github.actor }} -L 400 | awk '{print $1}'
        
        # echo "for i in ..."
        # for i in $(gh repo list --fork ${{ github.actor }} -L 300 | awk '{print $1}'); do
        #     echo ""
        #     echo $i
        #     # gh auth refresh -s workflow
        #     # gh repo sync $i
        #     if [ -n "$(gh repo sync $i | grep "workflow changes")" ];then
        #         gh auth refresh -s workflow
        #     fi
        #     echo ""
        # done

    # Tmate ##
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    
