name: Synk All Forks

# Controls when the workflow will run
on:
  schedule:
    - cron:  '30 2 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    # # Tmate ##
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    
    - name: Synk Forks
      run: |
        echo "Auth"
        echo ${{ secrets.synk_token }} | gh auth login --with-token
        
        
        #gh repo list ${{ github.actor }} -L 400 | awk '{print $1}'
        
        echo "for i in ..."
        for i in $(gh repo list --fork ${{ github.actor }} -L 300 | awk '{print $1}'); do
            echo ""
            echo $i
            gh repo sync $i
            echo ""
        done
